api:
  replicaCount: 1
  image:
    repository: noman666/todo-fastapi
    tag: "2.0"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8000
    nodePort: 30293

postgres:
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path

  database: tododb
  username: todo_user
  password: replace-with-a-strong-password

secrets:
  adminUsername: your-admin-username
  adminPassword: replace-with-a-strong-password
  secretKey: replace-with-a-long-random-secret

rbac:
  create: true