apiVersion: v1
kind: Secret
metadata:
  name: todo-app-api
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secrets.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}