apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}